### ISSUE TITLE
Object reference not set to an instance of an object.

### ISSUE THREAD

**Issue by erossini** [ThatCSharpGuy/MarkdownView#1]
Hi guys,
I'm trying to use your component but with every platform I'm receiving the some error:

> Object reference not set to an instance of an object.

In a new ContentPage I added the following code in the constructor:

            MarkdownView _webView;
            _webView = new MarkdownView()
            {
                Markdown = "## Hello!" + Environment.NewLine + "This is a new line.",
                HorizontalOptions = LayoutOptions.FillAndExpand,
                VerticalOptions = LayoutOptions.FillAndExpand,
            };
            _webView.Stylesheet = _stylesheets[0];

            this.Content = _webView;

The page is:

    <?xml version="1.0" encoding="utf-8" ?>
    <ContentPage xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             x:Class="WordBankEasy.Views.Page1">
      <ContentPage.Content>
          <Label Text="Test" />
      </ContentPage.Content>
    </ContentPage>

Thank you in advance

**Comment by erportico** [comment]
I think when I install your component, it is working only on UWP project. In the UWP project I can find a reference called **Xam.Plugins.Forms.MarkdownView**. In Droid project there is a reference called **ViewMarkdown.Forms.Pluigin.Droid**. But in iOS I have only a reference to **ViewMarkdown.Forms.Plugin.Abstractions**.

**Comment by fferegrino** [comment]
Let me check, I'll try to diagnose it asap.

**Comment by fferegrino** [comment]
I think I found the issue. My guess is that it is related to Xamarin.Forms' DependencyService. I'll try to use another way to register the dependencies needed instead of using the attribute.

**Comment by ferrydeboer** [comment]
@fferegrino I wanted to open another issue, but I have the same. It's the NuGet packages not installing properly for 0.1.0 . It only installs the abstractions.

- On Window (Phone) 8.1 there is not even a platform specific assembly being downloaded. It just picks the abstractions assembly as the right target.
- On iOS I also had to add the reference to the MonoTouch assembly myself.

**Steps to reproduce**
Just update your MrkViewer to 0.1.0 and try to run the Windows Project.

**Analysis**
I'm not an expert on nuget, but I see all the Windows Libs files are commented in the [nuspec](https://github.com/ThatCSharpGuy/MarkdownView/blob/master/ViewMarkdown.nuspec)

**Comment by fferegrino** [comment]
Can you please try to update again, this time to 0.1.2.1.

I do not have a proper setup to develop for Windows platform, but I think It'll work.

**Comment by ferrydeboer** [comment]
Awesome! Packages are installed ok now, so I can actually construct the MarkdownView.
It works perfectly as expected now when I update my own solution and when I have MrkViewer update to 0.1.2.1

Thanks!

**Comment by fferegrino** [comment]
Glad to hear that 😁 , I'm closing this issue now.
