### ISSUE TITLE
.NetStandard 2.0 

### ISSUE THREAD

**Issue by PostImpatica** [ThatCSharpGuy/MarkdownView#3]
Could this be updated to support .NetStandard 2.0?

**Comment by fferegrino** [comment]
I'll look into it :)

**Comment by fferegrino** [comment]
Done, this repository will no longer be active and the development has been moved to https://github.com/messier16/MarkdownView2

As for this issue, can you help me testing this package [Xam.Plugins.Forms.MarkdownView 1.0.0-beta](https://www.nuget.org/packages/Xam.Plugins.Forms.MarkdownView/1.0.0-beta)?
